config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  ####################################################################################################

  root "chatroom#index"
  # get "home", to: "pages#home"

  ## On the request 'get', asking for 'login', where does it route?
  # get "login", to: "sessions#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  post "messages", to: "messages#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { minimum: 1, maximum: 255 }

  # -> { ... } is Ruby's stabby lambda syntax :)
  # ChatGPT noticed this was inefficient. It loads all messages and then limits
  # scope :custom_display, -> { order(:created_at).last(20) }
  #
  # We will let the database do the limit
  scope :custom_display, -> { order(created_at: :desc).limit(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 15 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  ## We need to prevent a user navigating to unauthorized links via the URL
  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in to perfom that action!"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new
    # @messages = Message.all
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
      message = current_user.messages.build(message_params)

      if message.save
        ActionCable.server.broadcast("chatroom_channel", { value: message_render(message) })
        redirect_to root_path and return
      end
    end


    private

    def message_render(message)
      # render partial partial_name, locals { local_name: value }
      # this will inturn append the whole partial via the
      # chatroom_channel.js received method
      # render(partial: "message", locals: { message: message })
      # render_to_string(partial: "message", formats: [ :html ], locals: { message: message })
      render_to_string(partial: "message", locals: { message: message })
    end

    def message_params
      params.require(:message).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [ :new, :create ]
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have logged in!"
      redirect_to root_path
    else
      flash.now[:error] = "Incorrect login information!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out!"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in? then
      flash[:warning] = "You are already logged in!"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<div class= "ui segment container basic">

  <h2 class="ui icon header center aligned">
    <i class="circular users icon pink inverted"></i>
    Say something!
  </h2>

  <div class= "ui grid">

    <div class= "column twelve wide">

      <div class= "ui card raised fluid chatbox">
        <%# This will need to accommodate for scrolling %>
        <div class= "content" id= "messages">
          <div class= "ui feed" id= "message-container">
            <%# This renders the messages/_message partial %>
            <%# and creates an instance variable 'message' %>
            <%# to be used in the partial to access the class %>
            <%= render @messages %>
          </div>
        </div>
        
        <div class= "content extra">
          <%# method: :post %>
          <%# url: message_path %>
          <%# Use the model: Model_Name so Rails can infer the route and method %>
          <%= form_with model: Message, class: "ui reply form" do |f| %>
            <div class= "field">
              <div class="ui icon input fluid">
                <%= f.text_field :body %>
                <%#= f.button '<i class="comments link icon"></i>'.html_safe %>
              </div>
            </div>
          <% end %>
        </div>

      </div>
    </div>

    <div class= "column four wide">
      <div class= "ui card raised chatbox">
        <div class= "content">
          <div class="ui menu fluid inverted vertical tall">
            <a class="item active">
              Home
            </a>
            <a class="item">
              Messages
            </a>
            <a class="item">
              Friends
            </a>
          </div>
        </div>
      </div>
    </div>

  </div>


</div>

app/views/layouts/_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="ui <%= msg_type %> message floating">
    <i class="close icon"></i>
    <div class= "header"><%= msg %></div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Message Me" %></title>
    <%# https://gauger.io/fonticon/ %>
    <%# Load custom fav icon. Ensure 'load path' is defined in package.json %>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= yield :head %>


    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%#= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "semantic.min.css", "data-turbo-track": "reload" %>
    <%#= stylesheet_link_tag "fomantic-ui-css/semantic.min.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%#= javascript_include_tag "dist/jquery.min.js", "data-turbo-track": "reload", defer: true %>
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%#= javascript_include_tag "semantic.min.js", "data-turbo-track": "reload", defer: true %>
    
  </head>

  <body>

    <div class= "ui segments horizontal basic">

      <!-- reduce padding to fill out segment -->
      <div class= "ui segment compact" style= "padding: 2px;">

        <!-- table-cell to fit in segment -->
        <div class="ui menu vertical inverted small" style= "display: table-cell; height: 500px">

          <div class="item">
            <div class="header">Users</div>
            <div class="menu">
              <div class="item">
                <div class="ui button fluid small inverted basic pink">Sign up</div>
              </div>
              <div class="item">
                <%= link_to "Login", login_path, class: "ui button fluid small inverted basic" %>
              </div>
            </div>

            <div class= "ui item">
              <div class= "ui dropdown fluid floating">
                <i class= "icon dropdown"></i>
                Account 
                <div class="ui menu fluid">
                  
                  <% if logged_in? %>
                    <%= link_to "Logout", logout_path, class: "item", data: {turbo_method: :delete} %>
                  <% end %>
                  <div class= "item">Other</div>
                </div>
              </div>
            </div>
            
          </div>

          <div class="item">
            <div class="header">Nav</div>
            <div class="menu">
              <%= link_to "Chatroom", root_path, class: "item" %>
            </div>
          </div>

          <div class="item">
            <div class="header">Support</div>
            <div class="menu">
              <a class="item">E-mail Support</a>
              <a class="item"><i class="ca flag">FAQs</i></a>
            </div>
          </div>

        </div> <!-- menu side bar -->

      </div> <!-- segment -->
    
      <div class= "ui segment">
        <%= render "layouts/messages" %>
        <%= yield %>
      </div>

    </div> <!-- segments horizontal -->

  </body>

</html>

app/views/messages/_message.html.erb
<%# Because we need to shift 'messy' code from one file to another  %>
<%# Also, be aware that the instance variable is predefined!        %>
<%# ie, 'message' in this case                                      %>
<div class="event">
  <div class="content">
    <div class="summary">                  
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>